# Generated by Django 5.1 on 2024-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptant',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='adoptant_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='adoptant',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='adoptant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='adoptant_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='volunteer_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='volunteer_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
